name: 'Backstage TechDocs'
description: 'Generate and publish Backstage TechDocs.'
author: 'Staffbase GmbH'

inputs:
  entity-namespace:
    description: 'Entity Namespace'
    required: true
    default: 'default'
  entity-kind:
    description: 'Entity Kind'
    required: true
    default: 'Component'
  entity-name:
    description: 'Entity Name'
    required: true
  publisher-type:
    description: 'awsS3 | azureBlobStorage'
    required: false
  storage-name:
    description: 'In case of AWS/GCS, use the bucket name. In case of Azure, use container name.'
    required: false
  aws-region:
    description: 'AWS Region'
    required: false
    default: 'eu-central-1'
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: false
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: false
  azure-account-name:
    description: 'Azure Account Name'
    required: false
  azure-account-key:
    description: 'Azure Account Key'
    required: false
  additional-plugins:
    description: 'List of additional python plugins to use for site creation'
    required: false
  skip-publish:
    description: 'Indicates whether publish step should be skipped'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ -z "${{ inputs.entity-name }}" ]]; then
          echo "::error::entity-name is required"
          exit 1
        fi
        
        if [[ "${{ inputs.skip-publish }}" == "false" ]]; then
          if [[ -z "${{ inputs.publisher-type }}" ]]; then
            echo "::error::publisher-type is required when skip-publish is false"
            exit 1
          fi
          
          if [[ "${{ inputs.publisher-type }}" == "awsS3" ]]; then
            if [[ -z "${{ inputs.storage-name }}" || -z "${{ inputs.aws-access-key-id }}" || -z "${{ inputs.aws-secret-access-key }}" ]]; then
              echo "::error::storage-name, aws-access-key-id, and aws-secret-access-key are required for AWS S3 publishing"
              exit 1
            fi
          elif [[ "${{ inputs.publisher-type }}" == "azureBlobStorage" ]]; then
            if [[ -z "${{ inputs.storage-name }}" || -z "${{ inputs.azure-account-name }}" || -z "${{ inputs.azure-account-key }}" ]]; then
              echo "::error::storage-name, azure-account-name, and azure-account-key are required for Azure Blob Storage publishing"
              exit 1
            fi
          else
            echo "::error::publisher-type must be 'awsS3' or 'azureBlobStorage', got '${{ inputs.publisher-type }}'"
            exit 1
          fi
        fi

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: '22'

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Install mkdocs and mkdocs plugins
      shell: bash
      run: python -m pip install mkdocs-techdocs-core==1.*

    - name: Install additional plugins
      if: inputs.additional-plugins != ''
      shell: bash
      run: |
        for p in ${{ inputs.additional-plugins }}
        do
          python -m pip install $p
        done

    - name: Generate docs site
      shell: bash
      run: npx @techdocs/cli generate --no-docker --verbose

    - name: Publish TechDocs site to AWS S3
      if: inputs.skip-publish == 'false' && inputs.publisher-type == 'awsS3' && inputs.aws-access-key-id != '' && inputs.aws-secret-access-key != '' && inputs.aws-region != ''
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        npx @techdocs/cli publish --publisher-type ${{ inputs.publisher-type }} \
        --storage-name ${{ inputs.storage-name }} \
        --entity ${{ inputs.entity-namespace }}/${{ inputs.entity-kind }}/${{ inputs.entity-name }}

    - name: Publish TechDocs site to Azure Blob
      if: inputs.skip-publish == 'false' && inputs.publisher-type == 'azureBlobStorage' && inputs.azure-account-name != '' && inputs.azure-account-key != ''
      shell: bash
      run: |
        npx @techdocs/cli publish --publisher-type ${{ inputs.publisher-type }} \
        --storage-name ${{ inputs.storage-name }} \
        --entity ${{ inputs.entity-namespace }}/${{ inputs.entity-kind }}/${{ inputs.entity-name }} \
        --azureAccountName ${{ inputs.azure-account-name }} \
        --azureAccountKey ${{ inputs.azure-account-key }}

branding:
  icon: 'check-square'
  color: 'blue'
