name: Dependabot

on:
  pull_request:

jobs:
  dependabot:
    name: Auto Merge
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@v5.5.0
    with:
      force: true
    secrets:
      app_id: ${{ vars.STAFFBASE_ACTIONS_APP_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
