name: Dependabot

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependabot:
    name: Auto Merge
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@6e6c062d84ba4422de03d07b019b75c345f3606e # v17.1.0
    with:
      force: true
    secrets:
      app_id: ${{ vars.STAFFBASE_ACTIONS_APP_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
