name: Dependabot

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependabot:
    name: Auto Merge
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@9ea5ca06a1ef865b0af9745b47ea74b731b65fc5 # v13.4.1
    with:
      force: true
    secrets:
      app_id: ${{ vars.STAFFBASE_ACTIONS_APP_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
